### ISSUE TITLE
Fibaro App keeps crashing

### ISSUE THREAD

**Issue by bm480** [athombv/com.fibaro#192]
Hi!

Unfortunately, the app crashed while I was doing the following:

Fibaro Wall plug was turned off manually (using the button on the wall plug) yesterday evening. This morning I found that the Fibaro app keeps crashing.

This is the stack trace:

TypeError: Cannot read property 'instance' of undefined
    at Object.Homey.manager.on (/drivers/FGWPE-101/driver.js:104:42)
    at emitThree (events.js:135:13)
    at Object.emit (events.js:216:7)
    at /manager/flow.js:1:315
    at /helpers/client.js:1:1040
    at Array.forEach (<anonymous>)
    at process.<anonymous> (/helpers/client.js:1:1009)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Fibaro app version v1.5.13 and Homey 1.5.3.

**Comment by bm480** [comment]
A restart of Homey fixed it.

**Comment by bm480** [comment]
This morning I found that the app crashed again. So, reopening this issue.

**Comment by caseda** [comment]
Does something particular happen just before it craches? Like do you activate a flow to change the led's color

**Comment by bm480** [comment]
The FGWPE-101 is the Fibaro wallplug which I added recently. I've used the wall plug before to measure energy consumption of my tumble dryer, but stopped using it because the device generated too much traffic and made my Z-Wave network unstable. At least thats what I expected. However, my thought was that the tumble dryer was randomly drawing current while being in standbye mode so I considered it safe to re-purpose the wallplug to measure the energy consumption of my entertainment setup (consisting of amplifier, tv, multiple game consoles, an apple tv and a gaming pc).

Looking at the insights shows that energy consumption was alternating between 25 and 50 watts in standbye mode and 0 watts when the wallplug was turned off. In game mode the energy consumption was around 220 watts. Insight doesn't give me a clue about when the Fibaro app crashed.

**Comment by caseda** [comment]
that is why i asked if you created flows with it, if not that makes it a lot more strange (as in impossible strange) for the `instance` to not be there (or empty) on the line of where it happens.

as when i read your crash [(line: 104, character: 42](https://github.com/athombv/com.fibaro/blob/master/drivers/FGWPE-101/driver.js#L104)) then it tells me that it happens with a flow that gets activated where you change the color of the led when the plug is "on".

so please make sure you really don't have a flow (or _had_ a flow) that changes the color of the led

but in my time of creating drivers for z-wave (1,5 years) i have never, seen the instance be empty/not there.
but then again, everything needs a first time.

**Comment by RobinBol** [comment]
Note to self (or @caseda): check if node exists before trying to access its properties.

**Comment by caseda** [comment]
Let's just convert to sdkv2, that should fix it too(?) 😛

**Comment by RobinBol** [comment]
@bm480 can you confirm this is currently still an issue for you?

**Comment by RobinBol** [comment]
Closing this issue since the reporter does not seem to respond anymore, if you find this issue and this is still an issue for you please let us know!
