### ISSUE TITLE
Motion Sensor not stable on Homey 1.5.8

### ISSUE THREAD

**Issue by kvandenbogaerde** [athombv/com.fibaro#208]
Doing some tests on motion sensor... min. 30 secs between tests..
reset, motion --> OK, 
2nd motion --> not OK (but I see 3 messages on the zwave-dev-tools 3Tx/5Rx, but nothing in homeylog)
3rd motion --> OK
4th motion --> not OK (Zwave-dev-tools  5Tx/10Rx, homey-log : nothing)
5th motion --> OK
6th motion --> not OK
7th motion --> OK

So I see something coming in the Homey Zwave Dev Tool... bu nothing gets reported in Homey itself...

**Comment by kvandenbogaerde** [comment]
Maybe this can help :  ?

2018-03-13T19:30:02.103Z | Node[9]: Received application command for COMMAND_CLASS_SECURITY, data: 0x40
-- | --
2018-03-13T19:30:02.103Z | Node[9]: [COMMAND_CLASS_SECURITY] {}
2018-03-13T19:30:02.103Z | Node[9]: [COMMAND_CLASS_SECURITY] [SECURITY_NONCE_REPORT] {"type":"Buffer","data":[37,138,84,201,120,46,77,223]}
2018-03-13T19:30:02.104Z | Node[9]: sendData to COMMAND_CLASS_SECURITY, params 0x80258a54c9782e4ddf
2018-03-13T19:30:02.568Z | Node[9]: Received application command for COMMAND_CLASS_SECURITY, data: 0x811225a0718bf215fd01b2bea91d72809065668725df6c7d838218150f
2018-03-13T19:30:02.569Z | Node[9]: [COMMAND_CLASS_SECURITY] {"Initialization Vector byte":{"type":"Buffer","data":[18,37,160,113,139,242,21,253]},"Properties1 (Raw)":{"type":"Buffer","data":[1]},"Properties1":{"Sequence Counter":1,"Sequenced":false,"Second Frame":false},"Command byte":{"type":"Buffer","data":[178,190,169,29,114,128,144,101,102,135]},"Receivers nonce Identifier (Raw)":{"type":"Buffer","data":[37]},"Receivers nonce Identifier":37,"Message Authentication Code byte":{"type":"Buffer","data":[223,108,125,131,130,24,21,15]}}
2018-03-13T19:30:02.584Z | Node[9]: [COMMAND_CLASS_NOTIFICATION] {"V1 Alarm Type (Raw)":{"type":"Buffer","data":[0]},"V1 Alarm Type":0,"V1 Alarm Level (Raw)":{"type":"Buffer","data":[0]},"V1 Alarm Level":0,"Reserved (Raw)":{"type":"Buffer","data":[0]},"Notification Status (Raw)":{"type":"Buffer","data":[255]},"Notification Status":"On","Notification Type (Raw)":{"type":"Buffer","data":[7]},"Notification Type":"Home Security","Event (Raw)":{"type":"Buffer","data":[0]},"Event":0,"Properties1 (Raw)":{"type":"Buffer","data":[1]},"Properties1":{"Event Parameters Length":1,"Sequence":false},"Event Parameter":{"type":"Buffer","data":[8]},"Event (Parsed)":"Event inactive"}
2018-03-13T19:30:02.585Z | Node[9]: Decapsulated frame from COMMAND_CLASS_SECURITY to COMMAND_CLASS_NOTIFICATION, data 0x05000000ff07000108

**Comment by kvandenbogaerde** [comment]
Also this log : 

2018-03-13T19:39:02.653Z | Node[9]: Received application command for COMMAND_CLASS_SECURITY, data: 0x40
-- | --
2018-03-13T19:39:02.653Z | Node[9]: [COMMAND_CLASS_SECURITY] {}
2018-03-13T19:39:02.653Z | Node[9]: [COMMAND_CLASS_SECURITY] [SECURITY_NONCE_REPORT] {"type":"Buffer","data":[40,192,138,102,16,69,211,199]}
2018-03-13T19:39:02.654Z | Node[9]: sendData to COMMAND_CLASS_SECURITY, params 0x8028c08a661045d3c7
2018-03-13T19:39:03.647Z | Node[9]: Received application command for COMMAND_CLASS_SECURITY, data: 0x81c792def2a4094904e943b9fab58fdc8848ba28e1ab87663a86e8f1
2018-03-13T19:39:03.648Z | Node[9]: [COMMAND_CLASS_SECURITY] {"Initialization Vector byte":{"type":"Buffer","data":[199,146,222,242,164,9,73,4]},"Properties1 (Raw)":{"type":"Buffer","data":[233]},"Properties1":{"Sequence Counter":9,"Sequenced":false,"Second Frame":true},"Command byte":{"type":"Buffer","data":[67,185,250,181,143,220,136,72,186]},"Receivers nonce Identifier (Raw)":{"type":"Buffer","data":[40]},"Receivers nonce Identifier":40,"Message Authentication Code byte":{"type":"Buffer","data":[225,171,135,102,58,134,232,241]}}
2018-03-13T19:39:03.662Z | Node[9]: [COMMAND_CLASS_NOTIFICATION] {"V1 Alarm Type (Raw)":{"type":"Buffer","data":[0]},"V1 Alarm Type":0,"V1 Alarm Level (Raw)":{"type":"Buffer","data":[0]},"V1 Alarm Level":0,"Reserved (Raw)":{"type":"Buffer","data":[0]},"Notification Status (Raw)":{"type":"Buffer","data":[255]},"Notification Status":"On","Notification Type (Raw)":{"type":"Buffer","data":[7]},"Notification Type":"Home Security","Event (Raw)":{"type":"Buffer","data":[8]},"Event":8,"Properties1 (Raw)":{"type":"Buffer","data":[0]},"Properties1":{"Event Parameters Length":0,"Sequence":false},"Event (Parsed)":"Motion Detection, Unknown Location"}
2018-03-13T19:39:03.663Z | Node[9]: Decapsulated frame from COMMAND_CLASS_SECURITY to COMMAND_CLASS_NOTIFICATION, data 0x05000000ff070800
2018-03-13T19:39:33.519Z | Node[9]: Received application command for COMMAND_CLASS_SECURITY, data: 0x40
2018-03-13T19:39:33.520Z | Node[9]: [COMMAND_CLASS_SECURITY] {}
2018-03-13T19:39:33.520Z | Node[9]: [COMMAND_CLASS_SECURITY] [SECURITY_NONCE_REPORT] {"type":"Buffer","data":[41,124,182,48,35,92,145,216]}
2018-03-13T19:39:33.520Z | Node[9]: sendData to COMMAND_CLASS_SECURITY, params 0x80297cb630235c91d8
2018-03-13T19:39:33.973Z | Node[9]: Received application command for COMMAND_CLASS_SECURITY, data: 0x81556561b912fe9f6d220d63670f23d8d727b09729b8cdd6f512932e4f
2018-03-13T19:39:33.974Z | Node[9]: [COMMAND_CLASS_SECURITY] {"Initialization Vector byte":{"type":"Buffer","data":[85,101,97,185,18,254,159,109]},"Properties1 (Raw)":{"type":"Buffer","data":[34]},"Properties1":{"Sequence Counter":2,"Sequenced":false,"Second Frame":true},"Command byte":{"type":"Buffer","data":[13,99,103,15,35,216,215,39,176,151]},"Receivers nonce Identifier (Raw)":{"type":"Buffer","data":[41]},"Receivers nonce Identifier":41,"Message Authentication Code byte":{"type":"Buffer","data":[184,205,214,245,18,147,46,79]}}
2018-03-13T19:39:33.988Z | Node[9]: [COMMAND_CLASS_NOTIFICATION] {"V1 Alarm Type (Raw)":{"type":"Buffer","data":[0]},"V1 Alarm Type":0,"V1 Alarm Level (Raw)":{"type":"Buffer","data":[0]},"V1 Alarm Level":0,"Reserved (Raw)":{"type":"Buffer","data":[0]},"Notification Status (Raw)":{"type":"Buffer","data":[255]},"Notification Status":"On","Notification Type (Raw)":{"type":"Buffer","data":[7]},"Notification Type":"Home Security","Event (Raw)":{"type":"Buffer","data":[0]},"Event":0,"Properties1 (Raw)":{"type":"Buffer","data":[1]},"Properties1":{"Event Parameters Length":1,"Sequence":false},"Event Parameter":{"type":"Buffer","data":[8]},"Event (Parsed)":"Event inactive"}
2018-03-13T19:39:33.988Z | Node[9]: Decapsulated frame from COMMAND_CLASS_SECURITY to COMMAND_CLASS_NOTIFICATION, data 0x05000000ff07000108

**Comment by kvandenbogaerde** [comment]
Last log...

2018-03-13T19:38:04.224Z | Node[9]: Marked as offline
-- | --
2018-03-13T19:39:02.653Z | Node[9]: Received application command for COMMAND_CLASS_SECURITY, data: 0x40
2018-03-13T19:39:02.653Z | Node[9]: [COMMAND_CLASS_SECURITY] {}
2018-03-13T19:39:02.653Z | Node[9]: [COMMAND_CLASS_SECURITY] [SECURITY_NONCE_REPORT] {"type":"Buffer","data":[40,192,138,102,16,69,211,199]}
2018-03-13T19:39:02.654Z | Node[9]: sendData to COMMAND_CLASS_SECURITY, params 0x8028c08a661045d3c7
2018-03-13T19:39:03.647Z | Node[9]: Received application command for COMMAND_CLASS_SECURITY, data: 0x81c792def2a4094904e943b9fab58fdc8848ba28e1ab87663a86e8f1
2018-03-13T19:39:03.648Z | Node[9]: [COMMAND_CLASS_SECURITY] {"Initialization Vector byte":{"type":"Buffer","data":[199,146,222,242,164,9,73,4]},"Properties1 (Raw)":{"type":"Buffer","data":[233]},"Properties1":{"Sequence Counter":9,"Sequenced":false,"Second Frame":true},"Command byte":{"type":"Buffer","data":[67,185,250,181,143,220,136,72,186]},"Receivers nonce Identifier (Raw)":{"type":"Buffer","data":[40]},"Receivers nonce Identifier":40,"Message Authentication Code byte":{"type":"Buffer","data":[225,171,135,102,58,134,232,241]}}
2018-03-13T19:39:03.662Z | Node[9]: [COMMAND_CLASS_NOTIFICATION] {"V1 Alarm Type (Raw)":{"type":"Buffer","data":[0]},"V1 Alarm Type":0,"V1 Alarm Level (Raw)":{"type":"Buffer","data":[0]},"V1 Alarm Level":0,"Reserved (Raw)":{"type":"Buffer","data":[0]},"Notification Status (Raw)":{"type":"Buffer","data":[255]},"Notification Status":"On","Notification Type (Raw)":{"type":"Buffer","data":[7]},"Notification Type":"Home Security","Event (Raw)":{"type":"Buffer","data":[8]},"Event":8,"Properties1 (Raw)":{"type":"Buffer","data":[0]},"Properties1":{"Event Parameters Length":0,"Sequence":false},"Event (Parsed)":"Motion Detection, Unknown Location"}
2018-03-13T19:39:03.663Z | Node[9]: Decapsulated frame from COMMAND_CLASS_SECURITY to COMMAND_CLASS_NOTIFICATION, data 0x05000000ff070800
2018-03-13T19:39:33.519Z | Node[9]: Received application command for COMMAND_CLASS_SECURITY, data: 0x40
2018-03-13T19:39:33.520Z | Node[9]: [COMMAND_CLASS_SECURITY] {}
2018-03-13T19:39:33.520Z | Node[9]: [COMMAND_CLASS_SECURITY] [SECURITY_NONCE_REPORT] {"type":"Buffer","data":[41,124,182,48,35,92,145,216]}
2018-03-13T19:39:33.520Z | Node[9]: sendData to COMMAND_CLASS_SECURITY, params 0x80297cb630235c91d8
2018-03-13T19:39:33.973Z | Node[9]: Received application command for COMMAND_CLASS_SECURITY, data: 0x81556561b912fe9f6d220d63670f23d8d727b09729b8cdd6f512932e4f
2018-03-13T19:39:33.974Z | Node[9]: [COMMAND_CLASS_SECURITY] {"Initialization Vector byte":{"type":"Buffer","data":[85,101,97,185,18,254,159,109]},"Properties1 (Raw)":{"type":"Buffer","data":[34]},"Properties1":{"Sequence Counter":2,"Sequenced":false,"Second Frame":true},"Command byte":{"type":"Buffer","data":[13,99,103,15,35,216,215,39,176,151]},"Receivers nonce Identifier (Raw)":{"type":"Buffer","data":[41]},"Receivers nonce Identifier":41,"Message Authentication Code byte":{"type":"Buffer","data":[184,205,214,245,18,147,46,79]}}
2018-03-13T19:39:33.988Z | Node[9]: [COMMAND_CLASS_NOTIFICATION] {"V1 Alarm Type (Raw)":{"type":"Buffer","data":[0]},"V1 Alarm Type":0,"V1 Alarm Level (Raw)":{"type":"Buffer","data":[0]},"V1 Alarm Level":0,"Reserved (Raw)":{"type":"Buffer","data":[0]},"Notification Status (Raw)":{"type":"Buffer","data":[255]},"Notification Status":"On","Notification Type (Raw)":{"type":"Buffer","data":[7]},"Notification Type":"Home Security","Event (Raw)":{"type":"Buffer","data":[0]},"Event":0,"Properties1 (Raw)":{"type":"Buffer","data":[1]},"Properties1":{"Event Parameters Length":1,"Sequence":false},"Event Parameter":{"type":"Buffer","data":[8]},"Event (Parsed)":"Event inactive"}
2018-03-13T19:39:33.988Z | Node[9]: Decapsulated frame from COMMAND_CLASS_SECURITY to COMMAND_CLASS_NOTIFICATION, data 0x05000000ff07000108

**Comment by MatthewWaanders** [comment]
Hey there, thanks for reporting this issue! Could you please send us a screenshot of your device settings? It may help us in debugging this issue.

**Comment by kvandenbogaerde** [comment]
![image](https://user-images.githubusercontent.com/1833236/37403877-8219e5fa-2790-11e8-8693-ae1172b2ffaf.png)
![image](https://user-images.githubusercontent.com/1833236/37403914-9a084134-2790-11e8-86c9-83a34b04bb26.png)
![image](https://user-images.githubusercontent.com/1833236/37403939-a96d17e4-2790-11e8-9d24-a1912a96ecab.png)
![image](https://user-images.githubusercontent.com/1833236/37403962-b5b3a766-2790-11e8-8d55-c5f101e88bb6.png)

**Comment by phaeton82** [comment]
I have similar issues. Same version of homey 1.5.8.

**Comment by rvmuilekom69** [comment]
Same problem here, sometimes motion stays on. Now after some time stops detecting motion (blue led flashes so it detects motion). This is since the update to firmware. 1.5.8. After reset works ok for some time. (hours). Parameter changes are not updates in the device (for example turn of led).

**Comment by SnooZerken** [comment]
Same problems here. Motion stays on all the time.

**Comment by MatthewWaanders** [comment]
While working on the SDK2 version of this application I've had extensive time to test this device, and personally I haven't ran into this issue as of this moment. (yet?)
I'm fairly confident that this issue is fixed by moving to MeshDriver (the new version of Z-Wave driver).

I'd have to ask you to wait until the SDK2 rewrite of this application, and thank you for your patience in me getting back to you!

**Comment by phaeton82** [comment]
Hi Matthew, I still have issues. Could you maybe give a rough estimate of the ETA ?

**Comment by MatthewWaanders** [comment]
I won't dare to put a timeline or an ETA down, especially since internal testing has to happen and as you well know sometimes things take longer than expected. That said so far we've made good progress on the rewrite.
I understand you still have issues and I'll do my best to get the update to you ASAP.

**Comment by alphabase** [comment]
Having the same challenges, Homey Firmware Versie: 1.5.9

**Comment by alpol017** [comment]
Homey 1.5.9 , fibaro 17.
Same here, in dev I seeing that sensor send data, but in  devices nothing. Sometimes it shows YES motion, and it stays YES forever. Doesn’t show that there was cancel alarm. Why did I updated?!

**Comment by alpol017** [comment]
Neo, aeotec and fibaro’s non battery devices works great

**Comment by Fusionswe** [comment]
Homey 1.5.9 Running Sensor "FGMS-001-PLUS, Motion Sensor (Z-Wave Plus)"
Also have issues that the movement from the sensor is reporting in properly from time to time to homey even though it seems like the sensor is reporting it due to the longer visual indication.

**Comment by alpol017** [comment]
Update, Put two FGMS-001-PLUS near homey. Everything works perfectly, move it on 2-3 meters and it sometimes works, sometimes no, but in developer nodes I seeing that homey receives data from sensors.

**Comment by kvandenbogaerde** [comment]
I have the same conclusion as alpol017. In developer mode data comes in, but no reaction in Homey.

**Comment by alpol017** [comment]
Update, one of the sensors started to work correctly 10 meters away from homey. The second still works only near homey.

**Comment by Martinus81** [comment]
Sometimes works well and after a reboot of homey everything is fucked up. The motion alarm stays on, a restart from the fibaro app does not help (no matter how many times you try). I have a dirty solution to this problem: Disconnect the battery from the fibaro sensor and put it back. Now you have to test whether it works again, if not: do it again. I found it works again in one out or five times. And it remains stable until the next homey restart.

**Comment by alpol017** [comment]
And again, sometimes homey get motion or cancel motion alarm, sometimes not…

**Comment by DiedB** [comment]
I have started the SDKv2 version of this app on my Homey, and repaired all motion sensors. Same problem is still occuring (motion alarm status hangs, happens in both on and off state). Really annoying, I do not have physical switches to override these lights.

I will try removing the battery and see if it works. However, that should not be needed.

**Comment by alpol017** [comment]
Fibaro app 2.1 (beta) motion sensor works great!

**Comment by DiedB** [comment]
I still experience instability with v2.1.

**Comment by rvmuilekom69** [comment]
Here too. Motion sensor even needs a backup timer to switch it off. Don't know for sure it will turn off by it self (maybe it does, maybe it won't). Even the door/window contact sometimes gives me a false alarm. Only 2 fibro sensors I have give me problems while the rest Never gives me problems.

**Comment by alpol017** [comment]
A week ago I wrote that everything good on 2.1 but no. It has false alarm on v2.1 too. It can work good for 3 days, then no alarm cancelation or it doesn’t make alarm on, then again everything is good.

**Comment by TedTolboom** [comment]
@alpol017 when there is no response from the sensor, can you check the z-wave log at developer.athom.com/tools/z-wave (filtered on the node ID of the sensor) and post the logging (10-15 minutes) here at GH?

**Comment by TedTolboom** [comment]
@alpol107 thanks...

@matthewwaanders, the logging is pretty clear: yet another SECURITY_NONCE_REPORT handshake failure...

Can you support to get this finally fixed?; has been an reported issue since 1.2.0...

**Comment by TedTolboom** [comment]
> @TedTolboom
> I believe fix will take some time, so...
> Is there any way to add my motion sensors in non-secure mode? As I understand, it will works great without encryption?

If Athom focusses on this issue, they will have it solved on short term...

As far as I am aware, Fibaro does not have an option from device side to force unsecure inclusion.
