### ISSUE TITLE
No power consumption measured

### ISSUE THREAD

**Issue by robertraaijmakers** [athombv/com.fibaro#25]
The power consumption for the Wall Plug and the Dimmer 2 (and probably other Fibaro devices that support this) are not visible / measured.

**What dit you do**
- Added the Wall Plug
- Added the FGD-212 (Dimmer 2)

**What did you expect**
- That power consumption would be visible in insights
- That I could trigger a flow when power consumption changes

**What did actually happen**
- No power consumption visible in insights / in the device card
- No flow trigger card with power consumption

I created a branch that should add power consumption measurement for the FGD-212. But this is the same piece of code noted in the readme (as example) and used in the Wall Plug. And since the Wall Plug doesn't work I don't think the FGD-212 would work with the same piece of code.

**Comment by WeeJeWel** [comment]
![screen shot 2016-08-03 at 14 41 33](https://cloud.githubusercontent.com/assets/319873/17365789/644df552-5988-11e6-9f48-bfe805d57d00.png)

Do you have something else than the screenshot?

**Comment by robertraaijmakers** [comment]
Ok, fair enough, if I add it as an "other" it does measure power! :)
Why doesn't this work if I add it as a lamp (what if I want to toggle something when my light bulb in my lamp dies and the power voltage drops when the light should be on)?

**Comment by WeeJeWel** [comment]
That's a bug in Homey itself that will be fixed within some time :)

**Comment by robertraaijmakers** [comment]
Cool :)
Does that also include that the Fibaro Dimmer 2 will show the wattage then? The code is already added to the driver and merged since version 1.0.6 of the Fibaro app.

**Comment by WeeJeWel** [comment]
Yeah, when added as a socket, it should!

**Comment by RobinBol** [comment]
@robertraaijmakers could you confirm that this issue is solved for you?

**Comment by robertraaijmakers** [comment]
![screen shot 2016-08-11 at 8 49 45 pm](https://cloud.githubusercontent.com/assets/1773099/17600752/3d16f816-6005-11e6-9fd7-9b28c872da27.png)

Sorry, not solved yet. Power usage not visible when I add my Fibaro socket as a lamp.
Also there is no power usage visible for the Dimmer 2.

![screen shot 2016-08-11 at 8 53 49 pm](https://cloud.githubusercontent.com/assets/1773099/17600883/d7d96db6-6005-11e6-86ff-781e331e15ef.png)

**Comment by RobinBol** [comment]
Created generic issue as this is not only applicable to the Fibaro app: https://github.com/athombv/homey/issues/859
