### ISSUE TITLE
Fibaro Motion Sensor (non Z-Wave+) reporting too frequent (not according to settings) causing Z-wave instabilities

### ISSUE THREAD

**Issue by TedTolboom** [athombv/com.fibaro#70]
Follow-up trying to solve: https://github.com/athombv/com.greenwavesystems/issues/18

Homey Firmware v0.10.9
Greenwave App v1.0.6
Fibaro v1.0.16

I noticed that both my Fibaro Motion sensors are reporting LUX changes way to frequent compared to the settings of the motion sensor.

Settings Motion sensor (LUX threshold @ 20 Lux, LUX interval @ 600 seconds, wakeup interval @ 900 seconds)):
<img width="664" alt="schermafbeelding 2016-11-16 om 21 19 40" src="https://cloud.githubusercontent.com/assets/17163431/20364177/6d6a248c-ac42-11e6-99ad-0b00d954a172.png">

Example of too frequent reporting:

> Wed Nov 16 2016 15:41:03 GMT+0100 (CET),44.5
> Wed Nov 16 2016 15:41:05 GMT+0100 (CET),44.5
> Wed Nov 16 2016 15:41:27 GMT+0100 (CET),44.5
> Wed Nov 16 2016 15:41:34 GMT+0100 (CET),44.5
> Wed Nov 16 2016 15:41:38 GMT+0100 (CET),44.5
> Wed Nov 16 2016 15:41:43 GMT+0100 (CET),44.5
> Wed Nov 16 2016 15:41:45 GMT+0100 (CET),44.5

Full data set (multiple examples):
[entry_achter_lux.zip](https://github.com/athombv/com.fibaro/files/595817/entry_achter_lux.zip)

Insights does show some erratic behavior around 13:00 (with LUX variations below the defined threshold), it does not show the erratic behavior at 15:41 (shows as single data point..
<img width="1127" alt="schermafbeelding 2016-11-16 om 20 47 01" src="https://cloud.githubusercontent.com/assets/17163431/20364390/4371258a-ac43-11e6-9ab9-a504ac6d5829.png">

This sensor required a new battery 1 or 2 days ago... settings have been updated (checked with setting the LED at different color) directly afterwards (similar effect as before the battery replacement)....

This behaivior is identical on my second motion sensor.

=====
Hypothesis for the other Github issue mentioned (https://github.com/athombv/com.greenwavesystems/issues/18) is that due to the erratic data logging triggering directly a switch on (or off) command on a lamp connected to the powernode is trying to send too often a on command creating a deadlock...
My flows have been updated to only send a on command if the lamps are switched off (and vv)

**Comment by TedTolboom** [comment]
Just, once more, updated the settings of the motion sensors... and confirmed by changing the LED color...

Directly afterwards, I get similar erratic behavior:
> Wed Nov 16 2016 22:15:12 GMT+0100 (CET),56
> Wed Nov 16 2016 22:15:21 GMT+0100 (CET),55
> Wed Nov 16 2016 22:15:23 GMT+0100 (CET),56
> Wed Nov 16 2016 22:15:26 GMT+0100 (CET),55
> Wed Nov 16 2016 22:15:28 GMT+0100 (CET),56
> Wed Nov 16 2016 22:15:34 GMT+0100 (CET),55
> Wed Nov 16 2016 22:15:36 GMT+0100 (CET),56
> Wed Nov 16 2016 22:15:45 GMT+0100 (CET),55
> Wed Nov 16 2016 22:15:47 GMT+0100 (CET),56
> Wed Nov 16 2016 22:15:50 GMT+0100 (CET),55
> Wed Nov 16 2016 22:15:52 GMT+0100 (CET),56
> Wed Nov 16 2016 22:16:05 GMT+0100 (CET),55
> Wed Nov 16 2016 22:16:07 GMT+0100 (CET),56
> Wed Nov 16 2016 22:16:10 GMT+0100 (CET),55
> Wed Nov 16 2016 22:16:12 GMT+0100 (CET),56
> Wed Nov 16 2016 22:16:29 GMT+0100 (CET),55
> Wed Nov 16 2016 22:16:32 GMT+0100 (CET),56
> Wed Nov 16 2016 22:16:34 GMT+0100 (CET),55
> Wed Nov 16 2016 22:16:36 GMT+0100 (CET),56
> Wed Nov 16 2016 22:16:45 GMT+0100 (CET),55
> Wed Nov 16 2016 22:16:52 GMT+0100 (CET),38
> Wed Nov 16 2016 22:17:23 GMT+0100 (CET),51
> Wed Nov 16 2016 22:17:28 GMT+0100 (CET),56
> Wed Nov 16 2016 22:17:35 GMT+0100 (CET),57
> Wed Nov 16 2016 22:17:37 GMT+0100 (CET),56
> Wed Nov 16 2016 22:17:39 GMT+0100 (CET),57
> Wed Nov 16 2016 22:17:42 GMT+0100 (CET),56
> Wed Nov 16 2016 22:17:53 GMT+0100 (CET),55
> Wed Nov 16 2016 22:17:55 GMT+0100 (CET),56
> Wed Nov 16 2016 22:17:57 GMT+0100 (CET),55
> Wed Nov 16 2016 22:17:59 GMT+0100 (CET),56
> Wed Nov 16 2016 22:18:09 GMT+0100 (CET),55
> Wed Nov 16 2016 22:18:11 GMT+0100 (CET),56
> Wed Nov 16 2016 22:18:16 GMT+0100 (CET),57
> Wed Nov 16 2016 22:18:18 GMT+0100 (CET),56
> Wed Nov 16 2016 22:18:29 GMT+0100 (CET),55
> Wed Nov 16 2016 22:18:31 GMT+0100 (CET),56
> Wed Nov 16 2016 22:18:33 GMT+0100 (CET),55
> Wed Nov 16 2016 22:18:36 GMT+0100 (CET),56
> Wed Nov 16 2016 22:18:49 GMT+0100 (CET),55
> Wed Nov 16 2016 22:18:51 GMT+0100 (CET),56
> Wed Nov 16 2016 22:18:53 GMT+0100 (CET),55
> Wed Nov 16 2016 22:18:55 GMT+0100 (CET),56
> Wed Nov 16 2016 22:19:13 GMT+0100 (CET),55
> Wed Nov 16 2016 22:19:15 GMT+0100 (CET),56
> Wed Nov 16 2016 22:19:17 GMT+0100 (CET),55
> Wed Nov 16 2016 22:19:20 GMT+0100 (CET),56
> Wed Nov 16 2016 22:19:33 GMT+0100 (CET),55
> Wed Nov 16 2016 22:19:35 GMT+0100 (CET),56
> Wed Nov 16 2016 22:19:37 GMT+0100 (CET),55
> Wed Nov 16 2016 22:19:40 GMT+0100 (CET),56
> Wed Nov 16 2016 22:19:43 GMT+0100 (CET),57
> Wed Nov 16 2016 22:20:15 GMT+0100 (CET),51
> Wed Nov 16 2016 22:20:20 GMT+0100 (CET),57
> Wed Nov 16 2016 22:20:31 GMT+0100 (CET),58
> Wed Nov 16 2016 22:20:33 GMT+0100 (CET),57
> Wed Nov 16 2016 22:20:35 GMT+0100 (CET),58
> Wed Nov 16 2016 22:20:37 GMT+0100 (CET),56
> Wed Nov 16 2016 22:20:40 GMT+0100 (CET),57
> Wed Nov 16 2016 22:20:42 GMT+0100 (CET),56
> Wed Nov 16 2016 22:20:44 GMT+0100 (CET),57
> Wed Nov 16 2016 22:20:55 GMT+0100 (CET),58
> Wed Nov 16 2016 22:20:57 GMT+0100 (CET),56
> Wed Nov 16 2016 22:20:59 GMT+0100 (CET),58
> Wed Nov 16 2016 22:21:02 GMT+0100 (CET),56
> Wed Nov 16 2016 22:21:04 GMT+0100 (CET),57
> Wed Nov 16 2016 22:21:10 GMT+0100 (CET),58
> Wed Nov 16 2016 22:21:12 GMT+0100 (CET),57
> Wed Nov 16 2016 22:21:19 GMT+0100 (CET),58
> Wed Nov 16 2016 22:21:21 GMT+0100 (CET),57
> Wed Nov 16 2016 22:21:23 GMT+0100 (CET),58
> Wed Nov 16 2016 22:21:26 GMT+0100 (CET),57
> Wed Nov 16 2016 22:22:02 GMT+0100 (CET),56
> Wed Nov 16 2016 22:22:04 GMT+0100 (CET),57
> Wed Nov 16 2016 22:22:21 GMT+0100 (CET),56
> Wed Nov 16 2016 22:22:23 GMT+0100 (CET),48 

With same settings as mentioned above...
I am wondering wether the settings are correctly implemented / transferred to the motion sensors...

**Comment by caseda** [comment]
I don't have this issue at all with all my sensors, in what version of the app did you include the sensor(s)

and maybe it did not send properly, try holding it close to homey, wake it up, make sure the settings are changed from previous state, and then save while the sensor is awake

**Comment by TedTolboom** [comment]
I'm not completely sure... but since I have Insights data since September 7th, I would guess since v0.9.3 (I don't know which Fibaro app version was available at that moment)

Also after the battery update, I positioned the motion sensor close to Homey (~20 cm).. and updated the settings. 

Yesterday, I did exactly what you described (on recommendation of Phuturist); 20 cm from Homey, manual wake-up, save settings with LED color change (to e.g. Magenta), verification that motion is showing Magenta color, saved with LED again of, verification and re-position it...

**Comment by caseda** [comment]
There has been 2 updates in the meanwhile that could fix this issue old vs new

z-wave driver update 1.0.0 => 1.0.2 (not very likely)
number parsers removed from the parameters (likely, but strange it doesn't auto apply it on reboot of homey)

and one update still incoming, but that's not something for the parameters, just default tamper parameter fix.

so maybe try to at least re-pair one of the sensors (you will loose your insights sadly) and see if it fixes it.

**Comment by TedTolboom** [comment]
Strangely, the greenwave powernodes have been working really stable (several days without issues and with snappy response) since I re-paired them in the around October 20th.... 
So I would expect that the motion sensor erratic data reports would start around end of October. But if I closely check the data from the motion sensor, I see similar (erratic) data reports from the motion sensors directly after pairing them with Homey (after full reset on v0.9.3)...

So I can't fully correlate both observations...
I will give re-pairing a try this evening, after monitoring the data logging throughout the day....

**Comment by caseda** [comment]
that's why i think it's the parsers in the settings are still there internal for your sensor drivers, those parsers break the parameter, parsers where there in september when you added them.

**Comment by TedTolboom** [comment]
Brief update:

Actions taken:
- (re-) confirmed that the right parameters are stored on the motion sensors (by modifying the LED color)
- Updated my flows to prevent the erratic data reports from my motion sensors to send repetitive ON (or OFF) commands; added AND card to only send a switch on command if the lamp itself is switched off
- Luminance values were already averaged (2 data points) to smoothen fluctuation; I consider to even extend it to 3 data points.

Today Homey / Greenwave has been running again stable without stalling / breaking up and is responding directly without delays. I will disable my nightly Homey reboot to see if the stability will hold tomorrow.

On your suggestion I will re-pair my motion sensors tomorrow evening (don't have time today), to see if the parsers that were still part of the Z-wave driver at the moment that I added the motion sensors (back in September) are causing the erratic data reports.

**Comment by TedTolboom** [comment]
Another update:
Removed my 2 Fibaro motion sensors, rebooted Homey, updated to v1.0.1 and added the motion sensors again. 
Updated the parameters to below settings and verified the transmission by changing the LED color.
<img width="664" alt="schermafbeelding 2016-11-19 om 12 09 20" src="https://cloud.githubusercontent.com/assets/17163431/20455017/21c70e80-ae51-11e6-899f-a957093e54e0.png">
<img width="665" alt="schermafbeelding 2016-11-19 om 12 09 53" src="https://cloud.githubusercontent.com/assets/17163431/20455018/284019a0-ae51-11e6-9ae0-9e50f6c81d51.png">

Insights now shows the following graph... which can be explained by the Illumination threshold of 20 Lux... In principle no issue, since the switch level is 20 Lux (fluctuation is well above this level)...

Yet, I still see "erratic" data reports which I cannot explain by the setting I use (on both sensors)...
> Sat Nov 19 2016 11:54:38 GMT+0100 (CET),102
> Sat Nov 19 2016 11:54:40 GMT+0100 (CET),99
> Sat Nov 19 2016 11:54:44 GMT+0100 (CET),101
> Sat Nov 19 2016 11:54:46 GMT+0100 (CET),98
> Sat Nov 19 2016 11:54:49 GMT+0100 (CET),97
> Sat Nov 19 2016 11:54:51 GMT+0100 (CET),96
> Sat Nov 19 2016 11:54:57 GMT+0100 (CET),95
> Sat Nov 19 2016 11:55:02 GMT+0100 (CET),94
> Sat Nov 19 2016 11:55:13 GMT+0100 (CET),95
> Sat Nov 19 2016 11:55:24 GMT+0100 (CET),96
> Sat Nov 19 2016 11:55:35 GMT+0100 (CET),97
> Sat Nov 19 2016 11:55:46 GMT+0100 (CET),98
> Sat Nov 19 2016 11:55:50 GMT+0100 (CET),99
> Sat Nov 19 2016 11:56:30 GMT+0100 (CET),98
> Sat Nov 19 2016 11:56:48 GMT+0100 (CET),99
[entry_LUX_voor.zip](https://github.com/athombv/com.fibaro/files/601390/entry_LUX_voor.zip)

If this would go unfiltered through the flows, the Z-wave network will again be overloaded...
Since the parsers can be excluded... can it still be some delay in the Z-wave mesh (relayed the same data through different paths (including the slower Powernodes) to Homey, which does not recognise that it is from the same origen)

**Comment by caseda** [comment]
i just though of something when looking through your list.

could you try this for me:
change the values around,
so the seconds value in the lux treshold
and the lux value in the interval parameter

maybe this changed for some reason in the device's FW update

**Comment by TedTolboom** [comment]
LOL... starting to have a flashback memory.. ;-P

Just updated the parameters... let's see what happens.

**Comment by TedTolboom** [comment]
First results (Motion voor), with LUX threshold @ 600 LUX and LUX interval @ 20 seconds
> Wed Nov 23 2016 10:16:47 GMT+0100 (CET),32
> Wed Nov 23 2016 10:18:07 GMT+0100 (CET),33
> Wed Nov 23 2016 10:20:08 GMT+0100 (CET),34
> Wed Nov 23 2016 10:21:09 GMT+0100 (CET),35
> Wed Nov 23 2016 10:21:49 GMT+0100 (CET),36
> Wed Nov 23 2016 10:22:09 GMT+0100 (CET),45
> Wed Nov 23 2016 10:22:29 GMT+0100 (CET),36
> Wed Nov 23 2016 10:25:30 GMT+0100 (CET),37
> Wed Nov 23 2016 10:26:10 GMT+0100 (CET),38
> Wed Nov 23 2016 10:26:51 GMT+0100 (CET),39
> Wed Nov 23 2016 10:27:11 GMT+0100 (CET),40
> Wed Nov 23 2016 10:27:31 GMT+0100 (CET),41
> Wed Nov 23 2016 10:27:51 GMT+0100 (CET),42
> Wed Nov 23 2016 10:28:11 GMT+0100 (CET),43
> Wed Nov 23 2016 10:28:31 GMT+0100 (CET),44
> Wed Nov 23 2016 10:28:51 GMT+0100 (CET),45
> Wed Nov 23 2016 10:29:31 GMT+0100 (CET),46
> Wed Nov 23 2016 10:29:52 GMT+0100 (CET),47
> Wed Nov 23 2016 10:30:32 GMT+0100 (CET),48
> Wed Nov 23 2016 10:31:12 GMT+0100 (CET),49
> Wed Nov 23 2016 10:31:32 GMT+0100 (CET),50
> Wed Nov 23 2016 10:32:12 GMT+0100 (CET),51
> Wed Nov 23 2016 10:32:32 GMT+0100 (CET),52
> Wed Nov 23 2016 10:32:53 GMT+0100 (CET),53
> Wed Nov 23 2016 10:33:13 GMT+0100 (CET),54
> Wed Nov 23 2016 10:33:33 GMT+0100 (CET),55
> Wed Nov 23 2016 10:34:13 GMT+0100 (CET),56
> Wed Nov 23 2016 10:34:33 GMT+0100 (CET),57
> Wed Nov 23 2016 10:35:13 GMT+0100 (CET),58
> Wed Nov 23 2016 10:35:53 GMT+0100 (CET),59

Not really every 20 seconds a data point... But close enough.  
Can it be that reports of same value are not logged in insights?

I will let the sensor run for today with these settings...
I will also modify the settings of my second motion sensor to LUX threshold @ 0 LUX (disabled) and LUX interval @ 600 seconds... See what that brings..

**Comment by TedTolboom** [comment]
Second sensor seems to be running quite stable when set to LUX threshold @ 0 LUX (disabled) and LUX interval @ 600 seconds... 

> Wed Nov 23 2016 12:48:40 GMT+0100 (CET),37
> Wed Nov 23 2016 12:58:32 GMT+0100 (CET),19
> Wed Nov 23 2016 13:08:27 GMT+0100 (CET),14
> Wed Nov 23 2016 13:18:21 GMT+0100 (CET),20
> Wed Nov 23 2016 13:28:15 GMT+0100 (CET),25
> Wed Nov 23 2016 13:38:09 GMT+0100 (CET),28
> Wed Nov 23 2016 13:48:04 GMT+0100 (CET),20
> Wed Nov 23 2016 13:57:58 GMT+0100 (CET),12
> Wed Nov 23 2016 14:07:51 GMT+0100 (CET),9
> Wed Nov 23 2016 14:15:33 GMT+0100 (CET),35
> Wed Nov 23 2016 14:25:26 GMT+0100 (CET),27
> Wed Nov 23 2016 14:35:19 GMT+0100 (CET),17
> Wed Nov 23 2016 14:45:13 GMT+0100 (CET),13
> Wed Nov 23 2016 14:55:09 GMT+0100 (CET),23
> Wed Nov 23 2016 15:05:03 GMT+0100 (CET),25
> Wed Nov 23 2016 15:14:55 GMT+0100 (CET),26
> Wed Nov 23 2016 15:24:50 GMT+0100 (CET),17
> Wed Nov 23 2016 15:34:44 GMT+0100 (CET),19

Stable interval of 600 seconds as set... So is the illumination threshold setting the culprit?
I could try it with interval set at 0 and threshold set at 20 LUX, but can only try this / see the effect tomorrow... (when it's becomming light again)..

Any other suggestions?

**Comment by TedTolboom** [comment]
OK... settings updated for the motion sensor..  illumination interval set at 0 and threshold set at 20 LUX

According to the manual, I would expect only reports if the light intensity changed by more than 20 Lux...

> 40. ILLUMINATION REPORT THRESHOLD
> The parameter determines the change in light intensity level
> resulting in illumination report being sent to the main controller.
>  Available settings: 0 - 65535 (1 - 65535 lux; 0 = reports are not
> sent)
>  Default setting: 200 (200 lux)
>  Parameter size: 2 [byte]

Yet, I still get every change in light intensity... 1 LUX...

> Thu Nov 24 2016 08:29:56 GMT+0100 (CET),8
> Thu Nov 24 2016 08:31:36 GMT+0100 (CET),9
> Thu Nov 24 2016 08:33:57 GMT+0100 (CET),10
> Thu Nov 24 2016 08:35:58 GMT+0100 (CET),11
> Thu Nov 24 2016 08:37:18 GMT+0100 (CET),12
> Thu Nov 24 2016 08:38:39 GMT+0100 (CET),13
> Thu Nov 24 2016 08:39:59 GMT+0100 (CET),14
> Thu Nov 24 2016 08:41:40 GMT+0100 (CET),15
> Thu Nov 24 2016 08:43:00 GMT+0100 (CET),16
> Thu Nov 24 2016 08:43:41 GMT+0100 (CET),19
> Thu Nov 24 2016 08:44:41 GMT+0100 (CET),20
> Thu Nov 24 2016 08:45:41 GMT+0100 (CET),21
> Thu Nov 24 2016 08:47:02 GMT+0100 (CET),22
> Thu Nov 24 2016 08:49:02 GMT+0100 (CET),23
> Thu Nov 24 2016 08:49:43 GMT+0100 (CET),24
> Thu Nov 24 2016 08:51:03 GMT+0100 (CET),25
> Thu Nov 24 2016 08:51:23 GMT+0100 (CET),21
> Thu Nov 24 2016 08:52:03 GMT+0100 (CET),22
> Thu Nov 24 2016 08:53:44 GMT+0100 (CET),23
> Thu Nov 24 2016 08:55:25 GMT+0100 (CET),24

I searched at other domotica forums, but see similar results..
I will try a higher setting (100 LUX) and see if this is changing the reporting of the light intensity

**Comment by caseda** [comment]
If more flora have the same issue then it might be a device manual error, it's not like something changed in the firmware in updates, it is all stated the same. 

I'll see if I can get the same result when using a low value. 
See if I can get a stable formula out of it and add a parser, or change the description accordingly

Would like to hear what comes out of your 100 lux change

Asking fibaro about it is probably taking too long

**Comment by TedTolboom** [comment]
Doesn't seem to be doing anything... (LUX threshold at 100 LUX)
> Thu Nov 24 2016 15:54:27 GMT+0100 (CET),36
> Thu Nov 24 2016 15:56:07 GMT+0100 (CET),35
> Thu Nov 24 2016 15:57:28 GMT+0100 (CET),34
> Thu Nov 24 2016 15:59:29 GMT+0100 (CET),35
> Thu Nov 24 2016 15:59:49 GMT+0100 (CET),34
> Thu Nov 24 2016 16:00:29 GMT+0100 (CET),35
> Thu Nov 24 2016 16:00:49 GMT+0100 (CET),33
> Thu Nov 24 2016 16:01:49 GMT+0100 (CET),32
> Thu Nov 24 2016 16:02:30 GMT+0100 (CET),31
> Thu Nov 24 2016 16:03:10 GMT+0100 (CET),30
> Thu Nov 24 2016 16:03:30 GMT+0100 (CET),29
> Thu Nov 24 2016 16:04:10 GMT+0100 (CET),28
> Thu Nov 24 2016 16:04:50 GMT+0100 (CET),27
> Thu Nov 24 2016 16:05:31 GMT+0100 (CET),26
> Thu Nov 24 2016 16:07:11 GMT+0100 (CET),25
> Thu Nov 24 2016 16:08:12 GMT+0100 (CET),24
> Thu Nov 24 2016 16:09:32 GMT+0100 (CET),23

I will check, at home, that the settings are correctly transferred... yet, the wakeup time (7200 sec) has passed multiple times

**Comment by TedTolboom** [comment]
LUX threshold at 200 LUX:
> Fri Nov 25 2016 10:16:09 GMT+0100 (CET),214
> Fri Nov 25 2016 10:20:34 GMT+0100 (CET),259
> Fri Nov 25 2016 10:22:28 GMT+0100 (CET),288
> Fri Nov 25 2016 10:24:40 GMT+0100 (CET),316
> Fri Nov 25 2016 10:34:34 GMT+0100 (CET),489
> Fri Nov 25 2016 10:35:57 GMT+0100 (CET),518
> Fri Nov 25 2016 10:40:05 GMT+0100 (CET),579
> Fri Nov 25 2016 10:49:58 GMT+0100 (CET),586
> Fri Nov 25 2016 10:59:53 GMT+0100 (CET),583
> Fri Nov 25 2016 11:04:58 GMT+0100 (CET),514
> Fri Nov 25 2016 11:14:53 GMT+0100 (CET),486
> Fri Nov 25 2016 11:15:14 GMT+0100 (CET),437
> Fri Nov 25 2016 11:15:15 GMT+0100 (CET),486
> Fri Nov 25 2016 11:18:51 GMT+0100 (CET),421
> Fri Nov 25 2016 11:18:55 GMT+0100 (CET),460
> Fri Nov 25 2016 11:25:56 GMT+0100 (CET),518
> Fri Nov 25 2016 11:35:52 GMT+0100 (CET),554
> Fri Nov 25 2016 11:37:50 GMT+0100 (CET),511

Typical LUX changes > 28 LUX... which is not the 200 LUX

Sensor at 100 LUX, still showing same results:
> Fri Nov 25 2016 11:42:40 GMT+0100 (CET),171
> Fri Nov 25 2016 11:43:00 GMT+0100 (CET),170
> Fri Nov 25 2016 11:43:20 GMT+0100 (CET),169
> Fri Nov 25 2016 11:43:40 GMT+0100 (CET),168
> Fri Nov 25 2016 11:44:00 GMT+0100 (CET),164
> Fri Nov 25 2016 11:44:20 GMT+0100 (CET),167
> Fri Nov 25 2016 11:45:01 GMT+0100 (CET),165
> Fri Nov 25 2016 11:46:01 GMT+0100 (CET),162
> Fri Nov 25 2016 11:46:41 GMT+0100 (CET),161
> Fri Nov 25 2016 11:47:01 GMT+0100 (CET),163
> Fri Nov 25 2016 11:47:21 GMT+0100 (CET),164
> Fri Nov 25 2016 11:47:41 GMT+0100 (CET),165
> Fri Nov 25 2016 11:48:02 GMT+0100 (CET),167
> Fri Nov 25 2016 11:48:22 GMT+0100 (CET),169
> Fri Nov 25 2016 11:48:42 GMT+0100 (CET),171
> Fri Nov 25 2016 11:49:22 GMT+0100 (CET),172

I will update the sensor with 200 LUX to 100 LUX to see if it shows similar behavior.

**Comment by Keverjeroen** [comment]
I have a problem wit the Fibario multisensor (Zwave +) like TedTolboom descibes.

**Details here:** https://forum.athom.com/discussion/comment/38369/#Comment_38369
**And here:** https://forum.athom.com/discussion/comment/38473/#Comment_38473

It looks like the sensor (or homey) ignores the settings in '_Lichtsterkte rapportage drempel (LUX)_' all the time. And it looks like the sensor (or homey) ignores te settings in '_Lichtsterkte rapportage interval (seconden)_' when the lux vallue isn't changed.

**Comment by caseda** [comment]
it is definitely **not** ignoring the setting, it's only sending/receiving the wrong value for the threshold (drempel) to the sensor.
the interval works appropriately like it is supposed to, but gets "over ruled" by the wrong threshold value

don't have enough time to actively test it yet why it sends the wrong value, and what value. probably next week somewhere, or Robin can have a look at this ofcourse

**Comment by Keverjeroen** [comment]
Hi @caseda, did you had time to look in to this problem? LUX stil only sends once an hour and even changing the color of the led-light of the ZW+ motion sensor isn't working.. :(

**Comment by caseda** [comment]
@Keverjeroen the color of the led not changing is a totally other [issue](https://github.com/athombv/homey/issues/1145), and has got nothing to do with this issue

the issue described here is that the parameter of the setting is not taken good by the device (which might be a fibaro FW problem) and only the value of "1" is used inside the sensor for the lux threshold.

please follow the instruction i gave in the other issue as a work-a-round for your issue

**Comment by RobinBol** [comment]
Hi guys, just pushed a commit (not in app store yet, probably later today) that should fix the following settings:

`motion_sensor_sensitivity`
`motion_cancellation_delay`
`tamper_cancellation_delay`
`illumination_report_threshold`
`illumination_report_interval`
`temperature_report_threshold`
`temperature_measuring_interval`
`temperature_report_interval`
`temperature_offset`
`led_ambient_1`
`led_ambient_100`
`temperature_blue`
`temperature_red`

Could you try and let me know if this resolves this issue for you? Please, when saving the settings directly wake up your battery device manually (might be going something wrong with waiting for it to wake up out of itself and then setting the configuration on the device).

**Comment by RobinBol** [comment]
Update should be pushed to your Homeys coming hours, please let me know:)

**Comment by JesperJanssen** [comment]
After the update from yesterday it's still not working correctly. According to the settings below you would expect a data point for temperature every 30 minutes for both temperature as lux or a data point in case the lux changes 10 or more and the temperature 0,1 degrees.

As you can see I have no data points at all for the temperature on 5-jan-2017 and for the lux I sometimes have less data points as once every 30 minutes and sometimes more (even though the lux didn't change more than 10 lux). I'm starting to think that the settings in Homey are not correctly send to the motion sensor (maybe a mismatch or something).

My settings are:
![image](https://cloud.githubusercontent.com/assets/17165733/21697071/f6351130-d390-11e6-8695-9d47a3403a88.png)

And this is how my graph looks:
![image](https://cloud.githubusercontent.com/assets/17165733/21697233/a9711c62-d391-11e6-8d33-185794330bc0.png)

And the wake up time of the device is: 3600 seconds

**Comment by caseda** [comment]
if you follow this issue,
then the issue has got to do with "illumination threshold" specifically,
and i'm 90% sure the cause of bad FW on the sensors (not homey),
if you download the results (hold mouse on the three dots next to the name to download) you will probably see also some more results then the chart is showing you

what firmware do you have on your sensor, if you know that is. (is shown on the box it came in)

will go into full debug mode for this tomorrow (friday), but just thought of something that could be being busy with other people's settings. so at least have a huge starting point on this.
hopefully my version has this issue as wel (so odd to say that ), with FW 2.7

**Comment by caseda** [comment]
ok, i can now official confirm that the issue is Sensor FW related, for 100% sure.

i have not been able to reproduce the issue with my v2.7 FW sensor,
even though that does not have the fix of lux reporting too often this has come in 2.8 (latest update of the non z-wave plus)

unfortunately i cannot find any sites where the firmware change-log is represented, but did find a video where they show the change-log of the sensor up to v2.8:
[https://www.youtube.com/watch?v=ULah4-Lz7Qk&t=1m38s&ab_channel=mysmarthome-cba-pl](https://www.youtube.com/watch?v=ULah4-Lz7Qk)
the change log is view-able on 1:38 into the video

copied from video:
>2.8
>[fix] Fixed problem with too many reports from lux meter.
>[fix] Multichannel Associations are now sent even when there is no single node set in association group.
>2.7
>[fix] Removed error with wrong multichannel association frames.
>[fix] Corrected tamper notifications in seismograph mode.
>[fix] Improved range test.
>[fix] Minor Z-wave improvements
>2.6
>[fix] Corrected error with removing associations.

if you look into v2.7 update you also see "Minor Z-wave improvements"
this might fix the parameter not being set properly in the sensor.
the v2.8 update just makes sure it is not send too much.(?)

**Comment by JesperJanssen** [comment]
My sensor is a Z-wave + with I believe FW version 3.2. I had to continue posting my issue in this topic because my issued was closed and I was referred to this issue.

I believe it used to work when I only could set the settings using the raw configuration parameters. Which at the moment is not working anymore. 

When setting the following raw configuration parameters (40,2,50;42,2,600;60,1,5;62,2,600;66,2,65528;80,1,10;86,1,18;87,1,23) I get the message value is out of bounds. Which is not true when looking at the manual of the motion sensor.

**Comment by caseda** [comment]
did you wake up the sensor just **Before** you saved the parameters?

**Comment by JesperJanssen** [comment]
You are correct seems I was using a manual from a different version of the motion sensor (used to work though before there were device specific apps for the z-wave devices).

Now I entered the following raw configuration parameters:
40,2,20;42,2,1800;60,2,1;62,2,900;64,2,1800;80,1,10;86,2,17;87,2,18

So the color should turn red once the sensor records a temperature of above 18C but now it's still green and the temperature is 21C.

Do the raw configuration parameters overrule the other device specific settings because at the moment it does not seem that it does ?

**Comment by caseda** [comment]
did you do what i said on the first line of my previous message?

**Comment by JesperJanssen** [comment]
Yes, I pushed the wake up button three times and waited until the light on the sensor went off and clicked on save in the motion sensor settings tab.

But still no red light when motion is detected. Furthermore, I noticed that I now got an extra data point for the temperature in insights but that's the only data point for temperature in the past 24 hours.

I'm using the raw configuration parameters those will work because the parameters in the settings are not working like they should.

**Comment by caseda** [comment]
You need to press the save button while the LED is on, not after it is off again, then it is asleep again

**Comment by JesperJanssen** [comment]
I'm wondering if Athom is working on this problem. I have waited until a new firmware update but the newest update (Homey Firmware Version: 1.1.4) did not solved the problem.

With the settings below you would expect a temperature report being send to Homey every 10 minutes. However, I only have one data point and that's when I woke up the device. And me feeling is that the temperature in the app is also not updated every 10 minutes but at the same frequency as the insight graphs shows.

![image](https://cloud.githubusercontent.com/assets/17165733/22618190/d8e9b7cc-ead6-11e6-8813-4658796d6a6a.png)

**Comment by caseda** [comment]
@JesperJanssen still wondering why you post this issue here,
since it is not the same issue at all.

but anyway, did you try to re-add the sensor yet in 1.1.4,
there is a lot changed, including better handeling of parameters when a sensor is not awake fully (the issue you had before), and maybe there are still some faulty parameters in your sensor when you were busy with the raw parameters.
re-adding it will put it back into it's default state.

if you really don't want to re-add, change all settings to a random value, save, then change them back so all values are being send when the device accepts the parameters (on manual or automatic wake-up)

@RobinBol
this very issue (the issue OP is saying) could even be closed, as it is not an homey issue, but a sensor issue, fixed in a firmware update of the sensor

**Comment by JesperJanssen** [comment]
@Caseda My issue got closed and they redirected me to this issue. But after removing the device, rebooting Homey and adding the device again on Homey firmware version 1.1.4 everything seems to work now. Need to do some more testing but so far so good.

**Comment by RobinBol** [comment]
Closing this issue as it seems indeed to be related to the firmware of the sensor. If you encounter further issues please let us know.
